//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WE_Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public account()
        {
            this.comment = new HashSet<comment>();
            this.idea = new HashSet<idea>();
            this.reaction = new HashSet<reaction>();
            this.notification = new HashSet<notification>();
        }
    
        public int account_id { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public Nullable<int> state { get; set; }

        public string status {
            get { return state == 0 ? "QA Manager" : state == 1 ? "QA coordinator " : "Staff"; }
        }

        [DisplayName("Full name")]
        public string fname { get; set; }
        public Nullable<bool> gender { get; set; }
        public string _gender
        {
            get { return gender == true ? "Male" : "Female"; }
        }

        public Nullable<int> phone { get; set; }
        public string position { get; set; }
        public Nullable<int> department_id { get; set; }
        public byte[] img { get; set; }
    
        public virtual department department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comment> comment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<idea> idea { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reaction> reaction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<notification> notification { get; set; }
    }
}
